/*
jabali-api

Testing JabaliAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jabali_sdk

import (
	"context"
	"testing"

	openapiclient "github.com/barrygear/jabali"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_jabali_sdk_JabaliAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test JabaliAPIService CheckHealth", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.JabaliAPI.CheckHealth(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JabaliAPIService CreateGame", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.JabaliAPI.CreateGame(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JabaliAPIService DeleteGame", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var gameId string

		httpRes, err := apiClient.JabaliAPI.DeleteGame(context.Background(), gameId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JabaliAPIService GetGame", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var gameId string

		resp, httpRes, err := apiClient.JabaliAPI.GetGame(context.Background(), gameId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JabaliAPIService ListGames", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.JabaliAPI.ListGames(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JabaliAPIService UpdateGame", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var gameId string

		resp, httpRes, err := apiClient.JabaliAPI.UpdateGame(context.Background(), gameId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
