/*
jabali-api

API Proposal for Jabali.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jabalisdkgo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GamePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GamePostRequest{}

// GamePostRequest struct for GamePostRequest
type GamePostRequest struct {
	Name string `json:"name"`
	Displayname string `json:"displayname"`
	Url string `json:"url"`
}

type _GamePostRequest GamePostRequest

// NewGamePostRequest instantiates a new GamePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGamePostRequest(name string, displayname string, url string) *GamePostRequest {
	this := GamePostRequest{}
	this.Name = name
	this.Displayname = displayname
	this.Url = url
	return &this
}

// NewGamePostRequestWithDefaults instantiates a new GamePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGamePostRequestWithDefaults() *GamePostRequest {
	this := GamePostRequest{}
	return &this
}

// GetName returns the Name field value
func (o *GamePostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GamePostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GamePostRequest) SetName(v string) {
	o.Name = v
}

// GetDisplayname returns the Displayname field value
func (o *GamePostRequest) GetDisplayname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Displayname
}

// GetDisplaynameOk returns a tuple with the Displayname field value
// and a boolean to check if the value has been set.
func (o *GamePostRequest) GetDisplaynameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Displayname, true
}

// SetDisplayname sets field value
func (o *GamePostRequest) SetDisplayname(v string) {
	o.Displayname = v
}

// GetUrl returns the Url field value
func (o *GamePostRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GamePostRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GamePostRequest) SetUrl(v string) {
	o.Url = v
}

func (o GamePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GamePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayname"] = o.Displayname
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *GamePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"displayname",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGamePostRequest := _GamePostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGamePostRequest)

	if err != nil {
		return err
	}

	*o = GamePostRequest(varGamePostRequest)

	return err
}

type NullableGamePostRequest struct {
	value *GamePostRequest
	isSet bool
}

func (v NullableGamePostRequest) Get() *GamePostRequest {
	return v.value
}

func (v *NullableGamePostRequest) Set(val *GamePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGamePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGamePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGamePostRequest(val *GamePostRequest) *NullableGamePostRequest {
	return &NullableGamePostRequest{value: val, isSet: true}
}

func (v NullableGamePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGamePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


